CREATE OR REPLACE TABLE EDW_DEV.CIPEDW_CONFIG.BKF_RATECODES_CONFIG (
    RATECODE_FILTER VARCHAR(50)
);

-- Insert your rate code patterns (remove wildcards)
INSERT INTO EDW_DEV.CIPEDW_CONFIG.BKF_RATECODES_CONFIG (RATECODE_FILTER) VALUES
('STANBKF'),
('STABKFRF'),
('SPFBKF'),
('SWAVBKF'),
('PREFBKF'),
('PRFBKFMX'),
('PRFBKFVL'),
('OTAPBKF'),
('OTABBKFO');


...
FROM EDW_PRD.USER_DB.VW_SUMHOTELGUESTDAILYAGG SHR
INNER JOIN EDW_PRD.CIPEDW.DIMHOTELGUEST DHG
    ON SHR.GUESTNAMESOURCEID = DHG.GUESTNAMESOURCEID
    AND DHG.SITECODE = 'WLV' AND DHG.RECORDACTIVEFLAG = 'Y'
LEFT JOIN EDW_PRD.CIPEDW.REFHOTELGUESTEMAIL RHGE
    ON SHR.GUESTNAMESOURCEID = RHGE.GUESTNAMESOURCEID
    AND RHGE.SITECODE = 'WLV' AND RHGE.RECORDACTIVEFLAG = 'Y' AND RHGE.EMAILTYPE = 'EMAIL'
LEFT JOIN EDW_PRD.CIPEDW.REFHOTELGUESTPHONE RHGP
    ON SHR.GUESTNAMESOURCEID = RHGP.GUESTNAMESOURCEID
    AND RHGP.SITECODE = 'WLV' AND RHGP.RECORDACTIVEFLAG = 'Y' AND RHGP.PRIMARYFLAG = 'Y'
-- NEW JOIN
INNER JOIN EDW_DEV.CIPEDW_CONFIG.BKF_RATECODES_CONFIG CFG
    ON SHR.RATECODE ILIKE '%' || CFG.RATECODE_FILTER || '%'
WHERE SHR.SITECODE = 'WLV'
  AND SHR.RESERVATIONSTATUS = 'CHECKED IN'
  AND SHR.RESERVATIONDATE <> SHR.CHECKINDATE 
  AND SHR.RESERVATIONDATE = CURRENT_DATE()
  AND COALESCE(RHGP.PHONENUMBER,'') != ''
