-- Execution steps in order

-- STEP 1: Update BKFBUFFETRESERVATION if any BKF reservations are complete -- Move to separate DAG - Dependecy based onn competion of SUMDININGRESERVATION refresh
MERGE INTO EDW_DEV.CIPEDW_OUTBOUND.BKFBUFFETRESERVATION AS TGT
USING
    (
    SELECT DININGRESERVATIONID, STATUSCODE 
    FROM EDW_PRD.CIPEDW.SUMDININGRESERVATION
    WHERE BOOKEDBY='BKF'
    ) SRC
ON TGT.RESERVATIONID = SRC.DININGRESERVATIONID
WHEN MATCHED THEN
UPDATE SET 
TGT.BKF_RESERVATION_STATUS = SRC.STATUSCODE,
TGT.RECORDUPDATEDATETIME = CURRENT_TIMESTAMP(),
TGT.RECORDUPDATEUSERID = CURRENT_USER();


-- STEP 2: Identify eligible reservations with eligible rate code for BKF Promo, that are not yet captured into BKF table
MERGE INTO EDW_DEV.CIPEDW_OUTBOUND.BKFBUFFETRESERVATION AS TGT
USING
(
SELECT 
   DISTINCT
   SHR.GRIDNUM,
   SHR.PLAYERID,
   SHR.CONFIRMATIONNUMBER,
   SHR.RESERVATIONBEGINDATETIME AS CHECKINDATETIME,
   SHR.RESERVATIONENDDATETIME AS CHECKOUTDATETIME,
   SHR.RESERVATIONDATE AS BKFRESERVATIONDATE, 
   TIME('07:45:00') AS BKFRESERVATIONTIME,
   (SHR.ADULTSCOUNT + SHR.CHILDRENCOUNT) AS BKFPARTYSIZE,
   SHR.ROOMNUMBER,
   DHG.FIRSTNAME,
   DHG.LASTNAME,
   RHGE.EMAIL,
   REPLACE(REPLACE(RHGP.PHONENUMBER,' ', ''),'-','') AS PHONENUMBER,
   SHR.RATECODE
FROM EDW_PRD.USER_DB.VW_SUMHOTELGUESTDAILYAGG SHR
INNER JOIN EDW_PRD.CIPEDW.DIMHOTELGUEST DHG
          ON SHR.GUESTNAMESOURCEID = DHG.GUESTNAMESOURCEID
          AND DHG.SITECODE = 'WLV' AND DHG.RECORDACTIVEFLAG = 'Y'
LEFT JOIN EDW_PRD.CIPEDW.REFHOTELGUESTEMAIL RHGE
          ON SHR.GUESTNAMESOURCEID = RHGE.GUESTNAMESOURCEID
          AND RHGE.SITECODE = 'WLV' AND RHGE.RECORDACTIVEFLAG = 'Y' AND RHGE.EMAILTYPE = 'EMAIL'
LEFT JOIN EDW_PRD.CIPEDW.REFHOTELGUESTPHONE RHGP
          ON SHR.GUESTNAMESOURCEID = RHGP.GUESTNAMESOURCEID
          AND RHGP.SITECODE = 'WLV' AND RHGP.RECORDACTIVEFLAG = 'Y' AND RHGP.PRIMARYFLAG = 'Y'
WHERE SHR.SITECODE = 'WLV'
AND SHR.RESERVATIONSTATUS = 'CHECKED IN'
AND (SHR.RATECODE ILIKE '%STANBKF%' OR
     SHR.RATECODE ILIKE '%STABKFRF%' OR
     SHR.RATECODE ILIKE '%SPFBKF%' OR
     SHR.RATECODE ILIKE '%SWAVBKF%' OR
     SHR.RATECODE ILIKE '%PREFBKF%' OR
     SHR.RATECODE ILIKE '%PRFBKFMX%' OR
     SHR.RATECODE ILIKE '%PRFBKFVL%' OR
     SHR.RATECODE ILIKE '%OTAPBKF%' OR
     SHR.RATECODE ILIKE '%OTABBKFO%')
AND SHR.RESERVATIONDATE <> SHR.CHECKINDATE 
AND SHR.RESERVATIONSTATUS='CHECKED IN'
AND SHR.RESERVATIONDATE = CURRENT_DATE()
AND COALESCE(RHGP.PHONENUMBER,'') != ''
) SRC
ON COALESCE(TGT.GRIDNUM,-1)=COALESCE(SRC.GRIDNUM,-1)
AND COALESCE(TGT.CONFIRMATIONNUMBER,'')=COALESCE(SRC.CONFIRMATIONNUMBER,'')
WHEN NOT MATCHED THEN
INSERT 
(
GRIDNUM, PLAYERID, CONFIRMATIONNUMBER, CHECKINDATETIME, CHECKOUTDATETIME, BKFRESERVATIONDATE, BKFRESERVATIONTIME, BKFPARTYSIZE, ROOMNUMBER, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, RATECODE, RECORDINSERTDATETIME, RECORDINSERTUSERID
)
VALUES
(
SRC.GRIDNUM, SRC.PLAYERID, SRC.CONFIRMATIONNUMBER, SRC.CHECKINDATETIME, SRC.CHECKOUTDATETIME, SRC.BKFRESERVATIONDATE, SRC.BKFRESERVATIONTIME, SRC.BKFPARTYSIZE, SRC.ROOMNUMBER, SRC.FIRSTNAME, SRC.LASTNAME, SRC.EMAIL, SRC.PHONENUMBER, SRC.RATECODE,  CURRENT_TIMESTAMP(), 'SVC_PRD_AIRFLOW'
)
;



-- Step 3: Request "create reservation 7R API End point" for below set of reservations only
WITH BKF_COMPLETE AS
(SELECT DISTINCT CONFIRMATIONNUMBER FROM EDW_DEV.CIPEDW_OUTBOUND.BKFBUFFETRESERVATION WHERE COALESCE(BKF_RESERVATION_STATUS,'') = 'COMPLETE')
SELECT GRIDNUM, PLAYERID, BKF.CONFIRMATIONNUMBER, BKFRESERVATIONDATE, BKFRESERVATIONTIME, BKFPARTYSIZE, FIRSTNAME, LASTNAME, PHONENUMBER, EMAIL, CLIENTID
FROM EDW_DEV.CIPEDW_OUTBOUND.BKFBUFFETRESERVATION BKF
LEFT JOIN BKF_COMPLETE
ON BKF.CONFIRMATIONNUMBER = BKF_COMPLETE.CONFIRMATIONNUMBER
WHERE 1=1
--AND BKF.BKFRESERVATIONDATE = CURRENT_DATE()
AND BKF_COMPLETE.CONFIRMATIONNUMBER IS NULL
AND COALESCE(BKF.CLIENTID,'') =''
;


-- Step 4: Capture response into a temp table

Select * from EDW_DEV.CIPEDW_OUTBOUND.BKF7RAPIRESPONSESTAGE;

-- create or replace TABLE EDW_DEV.CIPEDW_OUTBOUND.BKF7RAPIRESPONSESTAGE (
-- GRIDNUM NUMBER(38,0),
-- PLAYERID NUMBER(38,0),
-- CONFIRMATIONNUMBER VARCHAR(255),
-- RESERVATION_ID VARCHAR(255),
-- RESERVATION_REFERENCE_CODE VARCHAR(255),
-- CLIENT_ID VARCHAR(255),
-- CLIENT_REFERENCE_CODE VARCHAR(255),
-- RESERVATION_CREATE_STATUS VARCHAR(255),
-- MSG VARCHAR(2000),
-- REQUEST_ID VARCHAR(255)
-- );


step3_qry = f"""
WITH BKF_COMPLETE AS
(SELECT DISTINCT CONFIRMATIONNUMBER FROM {EDW_DB_NAME}.CIPEDW_OUTBOUND.BKFBUFFETRESERVATION WHERE COALESCE(BKF_RESERVATION_STATUS,'') = 'COMPLETE')
SELECT GRIDNUM, PLAYERID, BKF.CONFIRMATIONNUMBER, BKFRESERVATIONDATE, BKFRESERVATIONTIME, BKFPARTYSIZE, FIRSTNAME, LASTNAME, PHONENUMBER, EMAIL
FROM {EDW_DB_NAME}.CIPEDW_OUTBOUND.BKFBUFFETRESERVATION BKF
LEFT JOIN BKF_COMPLETE
ON BKF.CONFIRMATIONNUMBER = BKF_COMPLETE.CONFIRMATIONNUMBER
WHERE 1=1
AND BKF.BKFRESERVATIONDATE = CURRENT_DATE()
AND BKF_COMPLETE.CONFIRMATIONNUMBER IS NULL
AND COALESCE(BKF.CLIENTID,'') =''
"""

dfEligibileHotelReservations =  SFModule.get_snowpark_df(step3_qry)

api_results = []  # To store results for writing back

# Collect Snowpark rows to local memory
rowsEligibileHotelReservations = dfEligibileHotelReservations.collect()

# Loop through each row and send as API request
for idx, row in enumerate(rowsEligibileHotelReservations):
    payload = {
        "date": row['BKFRESERVATIONDATE'],
        "time": row['BKFRESERVATIONTIME'],
        "party_size": row['BKFPARTYSIZE'],
        "first_name": row['FIRSTNAME'],
        "last_name": row['LASTNAME'],
        "phone": row['PHONENUMBER'],
        "email": row['EMAIL'],
        "loyality_id" : row['PLAYERID'],
        "notes" : row['CONFIRMATIONNUMBER'],
        'send_reminder_email': 'false',
        'send_reminder_sms':  'false',
        'access_persistent_id': access_persistent_id
    }

    try:

        response = requests.put(url, data=payload, headers=headers)
        result = response.json()
        if response.status_code == 200:
          # Handle successful response
          record = {
              "GRIDNUM": row['GRIDNUM'],
              "PLAYERID": row['PLAYERID'],
              "CONFIRMATIONNUMBER": row['CONFIRMATIONNUMBER'],
              "RESERVATION_ID": result.get("data", {}).get("reservation_id", ""),
              "RESERVATION_REFERENCE_CODE": result.get("data", {}).get("reservation_reference_code", ""),
              "CLIENT_ID": result.get("data", {}).get("client_id", ""),
              "CLIENT_REFERENCE_CODE": result.get("data", {}).get("client_reference_code", ""),
              "RESERVATION_CREATE_STATUS": "SUCCESS",
              "MSG": "",
              "REQUEST_ID": ""
          }
          api_results.append(record)
        else:
          # Error handling
          record = {
              "GRIDNUM": row['GRIDNUM'],
              "PLAYERID": row['PLAYERID'],
              "CONFIRMATIONNUMBER": row['CONFIRMATIONNUMBER'],
              "RESERVATION_ID": "",
              "RESERVATION_REFERENCE_CODE": "",
              "CLIENT_ID": "",
              "CLIENT_REFERENCE_CODE": "",
              "RESERVATION_CREATE_STATUS": "ERROR",
              "MSG": result.get("msg", ""),
              "REQUEST_ID": result.get("request_id", "")

          }
          api_results.append(record)
          
    except requests.exceptions.RequestException as e:
        # Catch hard failures only (e.g., timeout, DNS failure)
        print(str(e))    
        


if api_results:
  response_rows = [Row(**r) for r in api_results]
  response_df = sf_session.create_dataframe(response_rows)

  ## BKF Response Snowflake Stage Table
  snf_stg_table = f"{EDW_DB_NAME}.CIPEDW_OUTBOUND.BKF7RAPIRESPONSESTAGE"

  ## Truncate the stage table
  sf_session.sql(f"USE SCHEMA {EDW_DB_NAME}.CIPEDW_OUTBOUND").collect(); sf_session.sql(f"TRUNCATE TABLE {snf_stg_table}").collect()

  ## Log Final Snowpark Dataframe into Snowflake
  SFModule.write_snowpark_df_to_sf(response_df, snf_stg_table, writemode="append")

print("Step 4 completed - Log response from 7R API into Snowflake")




-- Step 5: Merge the API response to BKF Table EDW_DEV.CIPEDW_OUTBOUND.BKFBUFFETRESERVATION

MERGE INTO EDW_DEV.CIPEDW_OUTBOUND.BKFBUFFETRESERVATION AS TGT
USING
EDW_DEV.CIPEDW_OUTBOUND.BKF7RAPIRESPONSESTAGE SRC
ON COALESCE(TGT.GRIDNUM,-1)=COALESCE(SRC.GRIDNUM,-1)
AND COALESCE(TGT.PLAYERID,-1)=COALESCE(SRC.PLAYERID,-1)
AND COALESCE(TGT.CONFIRMATIONNUMBER,'')=COALESCE(SRC.CONFIRMATIONNUMBER,'')
WHEN MATCHED THEN
UPDATE SET
TGT.RESERVATIONID = SRC.RESERVATION_ID,
TGT.REFERENCECODE = SRC.RESERVATION_REFERENCE_CODE,
TGT.CLIENTID = SRC.CLIENT_ID,
TGT.CLIENTREFERENCECODE = SRC.CLIENT_REFERENCE_CODE,
TGT.API_ERROR_MESSAGE = SRC.MSG,
TGT.API_ERROR_REQUEST_ID = SRC.REQUEST_ID,
TGT.BKF_RESERVATION_CREATE_DTTM = CURRENT_TIMESTAMP(),
TGT.BKF_RESERVATION_CREATE_STATUS = SRC.RESERVATION_CREATE_STATUS,
TGT.RECORDUPDATEDATETIME = CURRENT_TIMESTAMP(),
TGT.RECORDUPDATEUSERID = 'SVC_PRD_AIRFLOW'
;







-- TRUNCATE TABLE EDW_DEV.CIPEDW_OUTBOUND.BKFBUFFETRESERVATION;
create or replace TABLE EDW_DEV.CIPEDW_OUTBOUND.BKFBUFFETRESERVATION (
	GRIDNUM NUMBER(38,0),
	PLAYERID NUMBER(38,0),
	CONFIRMATIONNUMBER VARCHAR(50),
    CHECKINDATETIME TIMESTAMP_NTZ(9),
    CHECKOUTDATETIME TIMESTAMP_NTZ(9),
    BKFRESERVATIONDATE DATE,
    BKFRESERVATIONTIME TIME,
    BKFPARTYSIZE NUMERIC,
	ROOMNUMBER VARCHAR(2000),
	FIRSTNAME VARCHAR(40),
	LASTNAME VARCHAR(40),
    EMAIL VARCHAR(40),
    PHONENUMBER VARCHAR(40),
    RATECODE VARCHAR(2000),
    RESERVATIONID VARCHAR(255),
    REFERENCECODE VARCHAR(20),
    CLIENTID VARCHAR(100),
    CLIENTREFERENCECODE VARCHAR(255),
    API_ERROR_MESSAGE VARCHAR(2000),
    API_ERROR_REQUEST_ID VARCHAR(255),
    BKF_RESERVATION_STATUS VARCHAR(20),
    BKF_RESERVATION_CREATE_DTTM TIMESTAMP_NTZ(9),
    BKF_RESERVATION_CREATE_STATUS VARCHAR(20),
	RECORDINSERTDATETIME TIMESTAMP_NTZ(9),
	RECORDINSERTUSERID VARCHAR(80),
	RECORDUPDATEDATETIME TIMESTAMP_NTZ(9),
	RECORDUPDATEUSERID VARCHAR(80),
	SOURCESYSTEMID NUMBER(38,0),
	JOBINSERTRUNID NUMBER(38,0),
	JOBUPDATERUNID NUMBER(38,0)  
);
