-- Already existing config table
CREATE OR REPLACE TABLE CONFIG_TABLE (
    CONFIG_KEY STRING,
    CONFIG_VALUE STRING
);

-- Insert config values
INSERT INTO CONFIG_TABLE (CONFIG_KEY, CONFIG_VALUE) VALUES
-- Site code
('SITE_CODE', 'WLV'),
-- Reservation status
('RESERVATION_STATUS', 'CHECKED IN'),
-- Phone number skip value
('PHONE_NUMBER_SKIP', ''),
-- Rate codes (one per row)
('RATECODE', '%STANBKF%'),
('RATECODE', '%STABKFRF%'),
('RATECODE', '%SPFBKF%'),
('RATECODE', '%SWAVBKF%'),
('RATECODE', '%PREFBKF%'),
('RATECODE', '%PRFBKFMX%'),
('RATECODE', '%PRFBKFVL%'),
('RATECODE', '%OTAPBKF%'),
('RATECODE', '%OTABBKF%');


WITH CONFIGS AS (
    SELECT
        MAX(CASE WHEN CONFIG_KEY = 'SITE_CODE' THEN CONFIG_VALUE END) AS SITE_CODE,
        MAX(CASE WHEN CONFIG_KEY = 'RESERVATION_STATUS' THEN CONFIG_VALUE END) AS RESERVATION_STATUS,
        MAX(CASE WHEN CONFIG_KEY = 'PHONE_NUMBER_SKIP' THEN CONFIG_VALUE END) AS PHONE_NUMBER_SKIP
    FROM CONFIG_TABLE
),
RATECODE_FILTERS AS (
    SELECT CONFIG_VALUE AS RATECODE
    FROM CONFIG_TABLE
    WHERE CONFIG_KEY = 'RATECODE'
)
SELECT *
FROM SHR
JOIN RHGP ON SHR.PLAYERID = RHGP.PLAYERID
JOIN CONFIGS
WHERE SHR.SITECODE = CONFIGS.SITE_CODE
  AND SHR.RESERVATIONSTATUS = CONFIGS.RESERVATION_STATUS
  AND EXISTS (
      SELECT 1
      FROM RATECODE_FILTERS
      WHERE SHR.RATECODE ILIKE RATECODE_FILTERS.RATECODE
  )
  AND SHR.RESERVATIONDATE <> SHR.CHECKINDATE
  AND SHR.RESERVATIONDATE = CURRENT_DATE
  AND COALESCE(RHGP.PHONENUMBER, '') = CONFIGS.PHONE_NUMBER_SKIP
ORDER BY GRIDNUM, PLAYERID, CONFIRMATIONNUMBER;
